In [1]:
import numpy as np

list1 =[1,2,3]
print(type(list1))

<class 'list'>


In [2]:
array1 = np.array(list1)

In [3]:
print(type(array1))
print(array1, array1.dtype)

<class 'numpy.ndarray'>
[1 2 3] int32


In [4]:
list2 = [1,2,3.0]
print(type(list2))
array2 = np.array(list2)
print(type(array2))
print(array2, array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1. 2. 3.] float64


In [5]:
array2

array([1., 2., 3.])

In [6]:
list3 = [1,2,'test']
array3 = np.array(list3)
print(array3, array3.dtype)


['1' '2' 'test'] <U11


In [14]:
#02-astype.py

array_int1 = np.array([1,2,3])
array_float1 = array_int1.astype('float64')
print(array_float1, array_float1.dtype)

array_float2 = np.array([1.1 ,2.1,3.1])
array_int2 =array_float2.astype('int32')
print(array_float2, array_float2.dtype)



[1. 2. 3.] float64
[1.1 2.1 3.1] float64


In [20]:
#03-reshape.py


#ndarray를 편리하게 생성하기 - arange, zeros, ones
#주로 테스트용으로 데이터 만들거나 대규모의 데이터를 일괄적으로
#초기화해야 할 경우에 사용된다.

#arange : 파이썬 표준 함수인 range()와 유사한 기능
sequence_array  = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

#reshape : ndarray 의차원과 크기를 변경 

array1 = np.arange(10)
print('array1:\n' , array1)

arrayA2 = array1.reshape(5,2)
print('arrayA2:\n', arrayA2)

#변경이 불가능하면 에러 발생
# arrayA3 = array1.reshape(4,3)


arrayB1 = array1.reshape(-1,5)
print('arrayB1 shape :' , arrayB1.shape)

arrayB2 = array1.reshape(5,-1)
print('arrayB2 shape :' , arrayB2.shape)

#3차원 ndarray
array2 = np.arange(8)
arrayC1 = array2.reshape((2,2,2))
print('arrayC1: \n', arrayC1)
print('arrayC1: \n' , arrayC1.tolist())

#3차원 ndarray를 2차원 ndaaray로 변화


[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)
array1:
 [0 1 2 3 4 5 6 7 8 9]
arrayA2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
arrayB1 shape : (2, 5)
arrayB2 shape : (5, 2)
arrayC1: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
arrayC1: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [24]:

#3차원 ndarray
array2 = np.arange(8)
arrayC1 = array2.reshape((2,2,2))
print('arrayC1: \n', arrayC1)
print('arrayC1: \n' , arrayC1.tolist())

#3차원 ndarray를 2차원 ndaaray로 변화
arrayC2 = arrayC1.reshape(-1,1)
print('arrayC2: \n', arrayC2.tolist())
print('arrayC2 shape:', arrayC2.shape )

#1차원 ndarray를 2차원 ndarray로 변환
arrayC3 = array2.reshape(-1, 1)
print('array2 : \n', array2)
print('array2: \n', array2.shape)
print('arrayC3 : \n', arrayC3.tolist())
print('arrayC3 shape:', arrayC3.shape)

arrayC1: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
arrayC1: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
arrayC2: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arrayC2 shape: (8, 1)
array2 : 
 [0 1 2 3 4 5 6 7]
array2: 
 (8,)
arrayC3 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arrayC3 shape: (8, 1)


In [29]:
#04-indexing.py

#인덱싱 - 데이터 세트 선택하기

#1에서 부터 9까지 1차원 ndarray 생성
array1 = np.arange(start =1, stop =10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)

print(type(value))

print('맨 뒤의 값:' , array1[-1])
print('맨 뒤에서 두번째 값:', array1[-2])

#ndarray 의 데이터값 수정
array1[0] =9
array1[8] =0
print('array1:', array1)

array1d = np.arange(start =1, stop =10)
array2d = array1d.reshape(3,3)
print(array2d, array2d.shape, array2d.ndim)

print('index 가리키느 값: ', array2d[0,0])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9
맨 뒤에서 두번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2
index 가리키느 값:  1


In [41]:
#slice.py

array1 = np.arange(start=1, stop=10)
array2 = array1[0:3]
print(array2)
print(type(array1))
print(type(array2))

array3 = array1[:3]
print(array3)

array4 = array1[3:]
print(array4)

array5 = array1[:]
print(array5)

array1d = np.arange(start=1 , stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[0:2, 0:2] \n', array2d[1:3, 0:3])
print('array2d[0:2, 0:2] \n', array2d[1:3, :])
print(array2d[:,:])
print( array2d[:2, 1:])
print( array2d[:2, 0])

print(array2d[0])
print(array2d[1])

print('array2d[0] shape:', array2d[0].shape)
print('array2d[1] shape:', array2d[1].shape)

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[0:2, 0:2] 
 [[4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]
1 [1 2 3]
[4 5 6]
array2d[0] shape: (3,)
array2d[1] shape: (3,)


In [42]:
print(array2d[0])
print(array2d[1])

[1 2 3]
[4 5 6]


In [50]:
import numpy as np

array1d = np.arange(start=1, stop =10)
array2d = array1d.reshape(3,3)
print(array2d)
arrayA1 = array2d[[0,1],2]
print('array2d[[0,1],2] => ', arrayA1.tolist())

arrayA1 = array2d[[0,1],0:2]
print('array2d[[0,1],2] => ', arrayA1.tolist())

arrayA3 = array2d[[0,1]]
print('array2d[[0,1],2] => ', arrayA3.tolist())

#boolean indexing

# [ ] 안에 array1d > 5 boolean indexing 을 적용
arrayB1 = array1d[array1d >5]
print('array1d > 5 불린 인덱싱 :', arrayB1)

array1d > 5

boolean_indexed = np.array([False, False,False, False, False,
                           True, True, True, True])
print(boolean_indexed)
arrayB2 = array1d[boolean_indexed]
print( arrayB2)

indexes = np.array([5,6,7,8])
arrayB3 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 : ', arrayB3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],2] =>  [[1, 2], [4, 5]]
array2d[[0,1],2] =>  [[1, 2, 3], [4, 5, 6]]
array1d > 5 불린 인덱싱 : [6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
일반 인덱스로 필터링 결과 :  [6 7 8 9]


In [6]:
#sort
import numpy as np
org_array = np.array([3,1,9,5])
print('행렬', org_array)

#np.sort() 정렬 - 원본 유지
sort_array1 = np.sort(org_array)
print(org_array)
print(sort_array1)

#ndarray.sort() 정렬 - 원본 변경 
sort_array2 = org_array.sort()
print(org_array)
print(sort_array2)

#내림차순 정렬 
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)


#------------------------------------------------------------------------------------------

array2d = np.array([[8,12],
                   [7,1]])

#로우 방향으로 정렬
sort_array2d_axis0 = np.sort(array2d, axis =0)
print(sort_array2d_axis0)

#컬럼 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis =1)
print(sort_array2d_axis1)

행렬 [3 1 9 5]
[3 1 9 5]
[1 3 5 9]
[1 3 5 9]
None
[9 5 3 1]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [11]:
#argsort

org_array  = np.array([3,1,9,5])

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스 : ', sort_indices)

sort_indieces_desc = np.argsort(org_array)[::-1] 
print('행렬 내림차순 정렬 시 원본 인덱스:' , sort_indieces_desc)

name_array  = np.array(['John', 'Mike', 'Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

#아주 유용한 코드임 
sort_indices_asc = np.argsort(score_array)
print('성정 오름차순 정렬 시 score_array의 인덱스: \n', sort_indices_asc)
print('성적 오름차순으로 이름 출력', name_array[sort_indices_asc]) 

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스 :  [1 0 3 2]
행렬 내림차순 정렬 시 원본 인덱스: [2 3 0 1]
성정 오름차순 정렬 시 score_array의 인덱스: 
 [0 2 4 1 3]
성적 오름차순으로 이름 출력 ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [16]:
#Operation.py

A = np.array([[1,2,3],
             [4,5,6]])

B = np.ones((2,3))

#배열 연결 - Row
#결과의 데이터 타입은 큰 쪽에 일치한다. 
R1 = np.r_[A,B]
print(R1)

#배열 연결 - col
R2 = np.c_[A,B]
print(R2)

#---------------------
#형태가 같은 ndarray 끼리는 사칙 연산을 적용할 수 있다. 
#데이터 타입은 역시 큰 쪽에 일치한다. 
print('------------')
R3 = A + B
print(R3)

R4 = A - B
print(R4)

R4 = A * B
print(R4)

R4 = A / B
print(R4)

R4 = A + 2 
print(R4)

R4 = A * 2
print(R4)

#사칙 연산에서는 배열 크기가 완전히 일치하지 않아도 한 쪽 차원의 길이가 
#1 또는 0이면 같은 값에 따라 자동으로 크기를 확장한 후 계산 한다. 

C = np.array([[1,2,3]])
print(A.shape)
print(C.shape)

#C 차원 임시로 확장 후 더하기
R9 = A + C
print(R9)
print(C.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3. 1. 1. 1.]
 [4. 5. 6. 1. 1. 1.]]
------------
[[2. 3. 4.]
 [5. 6. 7.]]
[[0. 1. 2.]
 [3. 4. 5.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
(1, 3)
[[2 4 6]
 [5 7 9]]
(1, 3)
